modLoader="javafml"
loaderVersion="[43,)" 
license="All rights reserved"
[[mods]] 
modId="arcana" 
version="${file.jarVersion}" 
displayName="Arcana" 
logoFile="arcana.png"
credits="Thanks to the original arcana team" 
authors="rocketraccon2004" 
description='''
Magic!
'''
[[dependencies.examplemod]] 
    modId="forge" 
    mandatory=true
    versionRange="[43,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
